// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZiPJkkhBHyC36I-LsQjKVyCAeEOFdWGQ',
    appId: '1:148397881301:web:3ef429140f34fbb3566f5c',
    messagingSenderId: '148397881301',
    projectId: 'my-ecommerce-app-43f51',
    authDomain: 'my-ecommerce-app-43f51.firebaseapp.com',
    databaseURL: 'https://my-ecommerce-app-43f51-default-rtdb.firebaseio.com',
    storageBucket: 'my-ecommerce-app-43f51.firebasestorage.app',
    measurementId: 'G-3VZ813NHDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhHCbH6Xxd__F7Tf4gqxK2vMokBqrEmYs',
    appId: '1:148397881301:android:02f5ea93ba981fd3566f5c',
    messagingSenderId: '148397881301',
    projectId: 'my-ecommerce-app-43f51',
    databaseURL: 'https://my-ecommerce-app-43f51-default-rtdb.firebaseio.com',
    storageBucket: 'my-ecommerce-app-43f51.firebasestorage.app',
  );

}